console.log(".-=~=-.                                                                 .-=~=-.");
console.log("(__  _)-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-(__  _)");
console.log("( _ __) Property of FlufCorp  Property of FlufCorp  Property of FlufCorp( _ __)");
console.log("(__  _)                                                                 (__  _)");
console.log("(_ ___)                   ♥Welcome to the credits page♥                 (_ ___)");
console.log("(__  _)                    This segment is made by                      (__  _)");
console.log("( _ __)                    Hong Wei from DCITP/1A/05                    ( _ __)");
console.log("(__  _)                   CEO of FlufCorp Pte Ltd 2022                  (__  _)");
console.log("(_ ___)   I will like to take my time to thank the reader for finding   (_ ___)");
console.log("(__  _)   this hidden menu and a big shoutout to Mr Daryl for all the   (__  _)");
console.log("( _ __)    help that I received during these lessons during the past    ( _ __)");
console.log("(__  _)                    few lessons. Therefore...                    (__  _)");
console.log("(_ ___)                                                                 (_ ___)");
console.log("(__  _)                                                                 (__  _)");
console.log("( _ __)                                                                 ( _ __)");
console.log("(__  _)                                                                 (__  _)");
console.log("(_ ___)                     Thank you for reading!!                     (_ ___)");
console.log("(__  _)         From the up and coming ethical hacker/programmer        (__  _)");
console.log("( _ __)                                                                 ( _ __)");
console.log("(__  _)                                                                 (__  _)");
console.log("( _ __)                                                                 ( _ __)");
console.log("(__  _) Property of FlufCorp  Property of FlufCorp  Property of FlufCorp(__  _)");
console.log("(_ ___)-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-(_ ___)");
console.log("`-._.-'                                                                 `-._.-'");